### ISSUE TITLE
Pitch Ideas: Let's Vote on a Project Lead by Project

### ISSUE THREAD

**Issue by Title-Pending** [The-Godot-Jamers/Ludam-Dare-41-Forums#2]
Ruben came up with this idea, plus "Slaughter Round" looks the theme, so we can come up with game ideas and vote this week which one we should pursue as a team.

**Comment by AlexHolly** [comment]
I dont think we are going to guess the theme I tried it once and even by picking multiple themes something strange will win.

We could simply decide what kind of game we want to make: Platformer, TopDown, Adventure, Runner, ...
and add some simple theme stuff later, the theme is only one Category.
![image](https://user-images.githubusercontent.com/4741886/38829509-8e443dec-41b9-11e8-9dd5-2073eadce213.png)

We could simply choose a few themes(we all like) and prepare for those and later we add something simple for the real theme.

We could also setup the project structure like godot version, CI builds what platforms we are going to release to. Who is going to do what. Deciding all that after the Jam started is wasted time.

![image](https://user-images.githubusercontent.com/4741886/38829664-207bf984-41ba-11e8-8976-cad78047ca80.png)

Here are my votes maybe we find common ground.

**Comment by Plopsiskopsis** [comment]
Platformer, TopDown, Adventure, Runner, ... I think platformer or topdown are good candidates considering the themes present. But im open to anything.

**Comment by Title-Pending** [comment]
I'm leaning towards top down or like a 3/4 view like scott pilgram vs the world. However, we have to consider if there is somethinh specific... meaning a mechanic that is bot an easy genre to pin... this could relate  things like puzzle design etc.
